const entries=[
['公司基础','Luvie 是一家什么公司？','Luvie Industry 是位于浙江海宁的墙板系统供应商，服务海外进口商、分销商、批发商和工程采购方。核心目标是建立专业信任，推动目录、样品、报价、订单和长期分销合作。','公司 介绍 工厂 海宁'],
['公司基础','哪些公司数据可以直接对外使用？','可确认使用：25年墙板制造经验、服务50多个国家、自有海宁生产基地、90%准时交付率、ISO 9001认证，以及OEM/ODM、贴牌包装和混柜订单能力。','25年 50国家 90% ISO 数据'],
['公司基础','统一对外联系方式是什么？','WhatsApp / Phone 统一使用 +30 6947135317。销售邮箱为 jinsburg@luvieindustry.com 和 globalsales@luvieindustry.com，官网为 luvieindustry.com。','电话 WhatsApp 邮箱 官网'],
['产品知识','Luvie 有哪些产品线？','六条核心产品线：PVC墙板、WPC木塑墙板、凹凸格栅板、PU文化石、UV高光大理石板和SPC地板。配套装饰条、线槽、方管等附件。','产品 PVC WPC 格栅 PU UV SPC'],
['产品知识','客户问 PVC 和 WPC 怎么选？','先问客户市场、应用场景、目标价位和外观偏好。PVC通常适合实用型快速翻新和入门级需求；WPC更适合重视木纹质感和中档室内效果的客户。具体性能按SKU确认。','PVC WPC 区别 怎么选',1],
['产品知识','怎样向客户解释质量控制？','把批准样品和订单规格作为标准，检查尺寸、型材结构、拼接、颜色、表面、包装和标签，并在出货前形成记录。可按要求安排第三方验货。','质量 质检 验货 色差'],
['销售SOP','收到新询盘后第一步做什么？','先判断客户类型、国家、目标市场、产品兴趣和采购阶段。至少追问产品类型、应用、尺寸或颜色、预计数量和交付国家。','询盘 新客户 第一步 客户判断'],
['销售SOP','客户直接问价格或 MOQ，怎么回复？','不要给通用数字。先询问国家、产品、尺寸或颜色、数量和应用，再由工厂确认对应SKU的价格与MOQ。','价格 MOQ 报价 起订量',1],
['销售SOP','样品政策怎么说？','可以讨论实物样品，样品费可在正式大货订单中全额抵扣。样品型号、尺寸、快递费和发出时间必须逐单确认。','样品 寄样 样品费',1],
['销售SOP','询盘回复后如何推进下一步？','每次回复必须有一个明确动作：补充规格、选择目录、确认样品、准备报价或约定跟进时间，并记录当前阶段和下一步。','跟进 下一步 CRM 目录'],
['内容SOP','Facebook 内容应该怎么写？','每条尽量包含产品、应用、客户类型、一个具体卖点和明确CTA。工厂口播可以直接，但必须画面与事实匹配；发布前由负责人确认。','Facebook 帖子 内容 发布'],
['内容SOP','一篇合格的 SEO/GEO 文章需要什么？','回答一个真实采购问题；开头直接给答案；加入第一手证据、决策表或清单、相关内链、作者与审核人、结构化数据，并以询盘动作结尾。','SEO GEO Google 文章'],
['内容SOP','Luvie 的视觉规范是什么？','纯白#FFFFFF、深炭灰#333639、浅灰#F2F3F4；暖木棕#A68C74只做按钮和小面积高亮。优先原创产品、工厂和场景素材。','设计 颜色 视觉 图片'],
['订单流程','订单合作的五步流程是什么？','提交询价 → 样品确认 → 签订中英文合同 → 生产与出货前质检 → FOB/CIF物流发货。所有具体费用、交期和规格按订单确认。','订单 流程 合同 生产 物流',1],
['红线规则','哪些动作绝对不能未经同意执行？','不能擅自发送WhatsApp或Email、发布Facebook、回复客户私信、修改正式官网、修改报价合同发票、删除客户数据、确认订单或付款。','禁止 红线 发送 发布 删除'],
['红线规则','客户资料如何保密？','客户姓名、邮箱、WhatsApp、采购量、报价、订单、价格、付款和物流信息默认保密。公开案例必须匿名化。','隐私 客户资料 保密'],
['红线规则','哪些产品承诺必须人工确认？','价格、MOQ、实时库存、生产交期、尺寸、性能等级、质保、目的国认证、防火等级和环保声明都必须按具体产品和订单确认。','承诺 认证 防火 库存 交期',1]
,
['安装与维护','PVC墙板安装前要确认什么？','先确认墙面或基层平整、干燥、清洁且结构稳定；核对安装方向、起始线、阴阳角、门窗收口、插座开孔和配套线条。潮湿区域必须额外确认接缝密封、防水基层和当地建筑规范。','安装 基层 墙面 工具 防水 收口',1],
['安装与维护','安装教程应该包含哪些步骤？','标准教程按“工具与材料 → 基层检查 → 测量排版 → 切割开孔 → 首板找平 → 拼接固定 → 阴阳角与收边 → 清洁验收”展开。每一步都要有近景、错误示范和关键尺寸，具体胶粘剂、钉距和伸缩缝按对应SKU说明书确认。','安装教程 步骤 切割 拼接 收边 胶水',1],
['安装与维护','PVC墙板如何日常清洁维护？','先用软布和中性清洁剂进行小面积测试，再擦拭表面；避免钢丝球、强研磨剂和未经验证的强溶剂。污渍、胶痕和消毒剂兼容性应以具体饰面和工厂测试为准。','清洁 维护 污渍 胶痕 清洁剂',1],
['技术资料','一个完整SKU资料包应包含什么？','至少包含白底产品图、纹理特写、截面与拼接图、场景图、尺寸厚度重量、包装装柜信息、安装说明、配件清单、检测或认证文件、清洁维护说明和可编辑营销素材。所有文件标注型号、版本和更新日期。','SKU 规格 技术参数 包装 认证 下载'],
['技术资料','防水、防火和环保卖点怎么使用？','防水或耐潮应区分材料本身、接缝系统和完整墙体结构；防火等级、烟密度、VOC或甲醛数据必须引用具体SKU、测试标准、报告编号和适用范围，不能把公司ISO认证当作产品性能报告。','防水 防火 环保 VOC 甲醛 报告',1],
['视频剪辑','Luvie短视频的标准结构是什么？','建议15至35秒：前2秒展示真实问题或结果；3至12秒呈现产品或安装动作；13至25秒给出防潮、耐污、易清洁或快速安装的可视化证据；结尾3秒自然露出Luvie、产品名称和询盘动作。不要用空泛口号代替证据。','视频 剪辑 短视频 结构 开头 CTA'],
['视频剪辑','已经加好字幕的真人口播由谁剪？','由欣荣直接完成：检查字幕和声音，添加不盖过人声的背景音乐及Luvie Logo，然后导出最终成片。Logo不能遮挡人物、产品、字幕或画面重点；字幕有明显错字、断句或遮挡时先反馈修改。完成后不再交给佳琳二次加工。','真人口播 已有字幕 欣荣 音乐 Logo 不需要佳琳'],
['视频剪辑','工厂介绍视频怎样剪、交给谁？','欣荣先检查并整理素材，不加字幕、不加背景音乐，完整保留机器声、操作声和现场交流声等同期声，再交给佳琳后续剪辑。交接时说明拍摄内容、重点环节、不可用片段，以及已知的发布用途或时长要求。','工厂介绍 工厂视频 同期声 不加字幕 不加音乐 欣荣 佳琳'],
['视频剪辑','AI故事类视频由谁负责？','AI故事类视频由佳琳独立完成全流程，包括故事结构、AI画面或视频素材、配音、字幕、音乐、音效、品牌元素和最终导出。欣荣不参与常规制作，除非负责人另有安排。','AI故事 AI视频 佳琳 独立生成 配音 字幕 音乐'],
['视频剪辑','剪辑画面、字幕和声音有什么要求？','竖版优先9:16，最低1080×1920；横版官网素材保留16:9母版。需要字幕的海外成片使用简短英文句子并留出安全边距；音乐只作氛围，产品声和口播必须清楚。工厂介绍类交接素材不加字幕和音乐，保留同期声。','画面 字幕 音乐 9:16 1080 剪辑'],
['视频剪辑','剪辑交付前检查什么？','核对产品型号、卖点证据、字幕拼写、品牌色、Logo、联系方式和CTA；删除夸张承诺、错误认证、未授权客户信息和无版权音乐。交付MP4成片、无字幕干净版、封面图、字幕文稿和原始工程或素材索引。','视频 检查 交付 封面 字幕 版权',1],
['视频剪辑','素材应该怎样命名和归档？','统一使用“日期_产品_场景_动作_版本”，例如2026-07-11_PVC_Bathroom_Cleaning_V01.mp4。原片、精选、工程、音乐、字幕、封面和成片分文件夹保存；未经确认的版本不得标记Final。','素材 命名 归档 Final 工程 原片']
];
const views={home:'首页',onboarding:'新员工入职',sop:'SOP中心',media:'资料中心',boss:'老板视图'};let state={view:'home',cat:'全部',q:'',selected:null};
const SB='https://czofweqqsoaoysjnmwrk.supabase.co',KEY='sb_publishable_GOrGFO4afPnarYG3d7wHDA_s0-0QWQM';
const app=document.querySelector('#app'),nav=document.querySelector('#nav');
function go(view){state.view=view;render()}document.addEventListener('click',e=>{const v=e.target.closest('[data-view]')?.dataset.view;if(v)go(v)});
function navHtml(){nav.innerHTML=Object.entries(views).map(([k,v])=>`<button data-view="${k}" class="${state.view===k?'active':''}">${v}</button>`).join('')}
function answer(e){return `<article class="answer"><header><span>${e[0]}</span>${e[4]?'<b>需要人工确认</b>':''}</header><h2>${e[1]}</h2><p>${e[2]}</p><footer>知识来源：Luvie 已确认知识与内部SOP</footer></article>`}
function home(){return `<section class="hero"><div><p class="eyebrow">LUVIE KNOWLEDGE OS</p><h1>公司的知识，<br><em>每个人都找得到。</em></h1><p class="lead">让新员工快速上手，让老板看清基础动作，让同事随时找到统一答案、SOP和资料。拿到网址即可全球访问，不绑定GPT邮箱或指定IP。</p></div><div class="role-grid"><button data-view="onboarding"><b>01</b><strong>我是新员工</strong><span>从公司、产品到红线，5天完成入门</span></button><button data-view="boss"><b>02</b><strong>我是老板</strong><span>查看基础动作、知识资产和执行重点</span></button><button data-view="sop"><b>03</b><strong>我要找答案</strong><span>搜索产品、客户回复、内容与订单流程</span></button></div></section><section class="searchbox"><label>直接问知识库</label><div class="searchrow"><input id="home-q" placeholder="例如：客户问MOQ怎么回复？"><button id="home-search">查答案</button></div><p class="hint">涉及价格、库存、交期和认证时，知识库会提示人工确认。</p><div id="home-answer"></div></section><section class="stats"><div><strong>25年</strong><span>制造经验</span></div><div><strong>50+</strong><span>服务国家</span></div><div><strong>90%</strong><span>准时交付</span></div><div><strong>6条</strong><span>核心产品线</span></div></section>`}
function onboarding(){const s=[['第1天','认识公司与产品','掌握公司定位、六条产品线、统一联系方式和已确认事实。'],['第2天','学习询盘处理','会判断客户、追问需求、选择目录，并识别高风险问题。'],['第3天','熟悉内容与品牌','理解Facebook、SEO/GEO和视觉规范。'],['第4天','理解订单流程','掌握询价、样品、合同、生产质检和物流发货。'],['第5天','通过红线检查','识别发送、发布、隐私、价格和承诺风险。']];return page('ONBOARDING','新员工 5 天入职路径','先理解公司为什么这样做，再学习每天怎么做。',`<div class="timeline">${s.map(x=>`<article><b>${x[0]}</b><h2>${x[1]}</h2><p>${x[2]}</p></article>`).join('')}</div><div class="notice"><strong>入职通过标准</strong>能正确介绍公司和产品；能处理基础询盘；能找到对应SOP；知道哪些动作需要负责人确认；不会擅自发送、发布或承诺。</div>`)}
function sop(){const cats=['全部',...new Set(entries.map(e=>e[0]))],list=entries.filter(e=>(state.cat==='全部'||e[0]===state.cat)&&(!state.q||`${e[1]} ${e[2]} ${e[3]}`.toLowerCase().includes(state.q.toLowerCase())));return page('SOP CENTER','统一动作，统一答案','搜索公司事实、产品知识、销售回复、内容规范、订单流程和红线规则。',`<div class="searchrow"><input id="sop-q" value="${state.q}" placeholder="输入问题、产品或工作动作"><button id="sop-search">搜索</button></div><div class="tabs">${cats.map(c=>`<button data-cat="${c}" class="${state.cat===c?'active':''}">${c}</button>`).join('')}</div>${state.selected?answer(state.selected):''}<div class="grid">${list.map((e,i)=>`<button class="card" data-entry="${entries.indexOf(e)}"><small>${e[0]}</small><h2>${e[1]}</h2><p>${e[2].slice(0,75)}…</p></button>`).join('')}</div>`)}
function media(){return page('RESOURCE CENTER','图片、视频与文档资料中心','团队成员可以直接上传和查看；上传后会进入统一图片库与文件库。',`<div class="media-layout"><form id="upload-form" class="upload-card"><h2>上传新资料</h2><label>资料标题<input name="title" required maxlength="120" placeholder="例如：PVC墙板纹理图"></label><div class="form-pair"><label>分类<select name="category"><option>产品图片</option><option>工厂现场</option><option>项目案例</option><option>培训视频</option><option>产品目录</option><option>SOP文件</option><option>其他</option></select></label><label>上传人<input name="uploaded_by" required maxlength="40" placeholder="姓名或部门"></label></div><label>标签<input name="tags" maxlength="300" placeholder="PVC, 木纹, 客厅"></label><label>说明<textarea name="description" maxlength="600" rows="3" placeholder="这份资料适合谁、什么时候使用"></textarea></label><label class="file-drop">选择图片、视频或文档<input name="file" type="file" required accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,application/pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx"><span>支持图片、MP4/WebM、PDF和Office文档，单文件不超过50MB</span></label><button class="primary upload-btn">上传到资料库</button><p id="upload-status" class="hint"></p></form><section class="library"><div class="library-head"><div><p class="eyebrow">TEAM ASSETS</p><h2>团队图片库</h2></div><select id="asset-filter"><option>全部</option><option>产品图片</option><option>工厂现场</option><option>项目案例</option><option>培训视频</option><option>产品目录</option><option>SOP文件</option><option>其他</option></select></div><div id="asset-grid" class="asset-grid"><p class="hint">正在读取资料…</p></div></section></div>`)}
function boss(){const cards=[['销售基础','每条询盘都有下一步','判断客户类型；问清产品和数量；明确目录、样品或报价；记录跟进时间。'],['内容基础','内容是否指向询盘','具体产品和客户；真实证据；统一CTA；负责人审核后发布。'],['交付基础','承诺是否有依据','价格、MOQ和库存逐单确认；样品合同一致；质检记录完整。'],['知识资产',`${entries.length} 条核心知识`,'覆盖公司、产品、销售、内容、订单与红线；配套5天入职路径。']];return page('MANAGEMENT VIEW','老板需要看清的基础动作','不是看热闹数据，而是确认团队有没有按统一方法持续执行。',`<div class="grid boss">${cards.map(x=>`<article class="card"><small>${x[0]}</small><h2>${x[1]}</h2><p>${x[2]}</p></article>`).join('')}</div>`)}
function page(k,t,c,body){return `<section class="section"><header class="page-head"><p class="eyebrow">${k}</p><h1>${t}</h1><p class="lead">${c}</p></header>${body}</section>`}
async function loadAssets(category='全部'){const grid=document.querySelector('#asset-grid');if(!grid)return;try{const r=await fetch(`${SB}/rest/v1/assets?select=*&order=created_at.desc`,{headers:{apikey:KEY}});if(!r.ok)throw Error('读取失败');let items=await r.json();if(category!=='全部')items=items.filter(x=>x.category===category);grid.innerHTML=items.length?items.map(assetCard).join(''):'<div class="empty">还没有资料，上传第一份吧。</div>'}catch{grid.innerHTML='<div class="empty">资料读取失败，请稍后刷新。</div>'}}
function assetCard(a){const url=`${SB}/storage/v1/object/public/knowledge-assets/${a.storage_path.split('/').map(encodeURIComponent).join('/')}`,isImg=a.content_type.startsWith('image/'),isVideo=a.content_type.startsWith('video/');const preview=isImg?`<img src="${url}" alt="${esc(a.title)}" loading="lazy">`:isVideo?`<video src="${url}" controls preload="metadata"></video>`:`<div class="doc-icon">${a.content_type.includes('pdf')?'PDF':'DOC'}</div>`;return `<a class="asset-card" href="${url}" target="_blank" rel="noreferrer"><div class="asset-preview">${preview}</div><div class="asset-info"><small>${esc(a.category)}</small><h3>${esc(a.title)}</h3><p>${esc(a.description||a.file_name)}</p><footer>${esc(a.uploaded_by)} · ${new Date(a.created_at).toLocaleDateString('zh-CN')}</footer></div></a>`}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function uploadAsset(form){const status=document.querySelector('#upload-status'),button=form.querySelector('button');const data=new FormData(form),file=data.get('file');if(file.size>52428800){status.textContent='文件超过50MB，请压缩后重试。';return}button.disabled=true;button.textContent='正在上传…';status.textContent='请不要关闭页面。';const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}-${safe}`;try{let r=await fetch(`${SB}/storage/v1/object/knowledge-assets/${path}`,{method:'POST',headers:{apikey:KEY,'Content-Type':file.type||'application/octet-stream','x-upsert':'false'},body:file});if(!r.ok)throw Error((await r.json()).message||'文件上传失败');const record={title:data.get('title'),description:data.get('description')||'',category:data.get('category'),tags:data.get('tags')||'',file_name:file.name,storage_path:path,content_type:file.type||'application/octet-stream',size_bytes:file.size,uploaded_by:data.get('uploaded_by')};r=await fetch(`${SB}/rest/v1/assets`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json','Prefer':'return=minimal'},body:JSON.stringify(record)});if(!r.ok)throw Error('资料登记失败');form.reset();status.textContent='上传成功，资料已进入图片库。';await loadAssets()}catch(e){status.textContent=`上传失败：${e.message}`}finally{button.disabled=false;button.textContent='上传到资料库'}}
function bind(){document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{state.cat=b.dataset.cat;render()});document.querySelectorAll('[data-entry]').forEach(b=>b.onclick=()=>{state.selected=entries[+b.dataset.entry];render()});const hs=document.querySelector('#home-search');if(hs)hs.onclick=()=>{const q=document.querySelector('#home-q').value.trim();const e=entries.find(x=>`${x[1]} ${x[2]} ${x[3]}`.toLowerCase().includes(q.toLowerCase()))||entries[0];document.querySelector('#home-answer').innerHTML=answer(e)};const ss=document.querySelector('#sop-search');if(ss)ss.onclick=()=>{state.q=document.querySelector('#sop-q').value.trim();render()};const uf=document.querySelector('#upload-form');if(uf){uf.onsubmit=e=>{e.preventDefault();uploadAsset(uf)};document.querySelector('#asset-filter').onchange=e=>loadAssets(e.target.value);loadAssets()}}
function render(){navHtml();app.innerHTML=state.view==='home'?home():state.view==='onboarding'?onboarding():state.view==='sop'?sop():state.view==='media'?media():boss();bind();scrollTo({top:0,behavior:'smooth'})}render();
