const entries=[
['公司基础','Luvie 是一家什么公司？','Luvie Industry 是位于浙江海宁的墙板系统供应商，服务海外进口商、分销商、批发商和工程采购方。核心目标是建立专业信任，推动目录、样品、报价、订单和长期分销合作。','公司 介绍 工厂 海宁'],
['公司基础','哪些公司数据可以直接对外使用？','可确认使用：25年墙板制造经验、服务50多个国家、自有海宁生产基地、90%准时交付率、ISO 9001认证，以及OEM/ODM、贴牌包装和混柜订单能力。','25年 50国家 90% ISO 数据'],
['公司基础','统一对外联系方式是什么？','WhatsApp / Phone 统一使用 +30 6947135317。销售邮箱为 jinsburg@luvieindustry.com 和 globalsales@luvieindustry.com，官网为 luvieindustry.com。','电话 WhatsApp 邮箱 官网'],
['产品知识','Luvie 有哪些产品线？','六条核心产品线：PVC墙板、WPC木塑墙板、凹凸格栅板、PU文化石、UV高光大理石板和SPC地板。配套装饰条、线槽、方管等附件。','产品 PVC WPC 格栅 PU UV SPC'],
['产品知识','客户问 PVC 和 WPC 怎么选？','先问客户市场、应用场景、目标价位和外观偏好。PVC通常适合实用型快速翻新和入门级需求；WPC更适合重视木纹质感和中档室内效果的客户。具体性能按SKU确认。','PVC WPC 区别 怎么选',1],
['产品知识','怎样向客户解释质量控制？','把批准样品和订单规格作为标准，检查尺寸、型材结构、拼接、颜色、表面、包装和标签，并在出货前形成记录。可按要求安排第三方验货。','质量 质检 验货 色差'],
['销售SOP','收到新询盘后第一步做什么？','先判断客户类型、国家、目标市场、产品兴趣和采购阶段。至少追问产品类型、应用、尺寸或颜色、预计数量和交付国家。','询盘 新客户 第一步 客户判断'],
['销售SOP','客户直接问价格或 MOQ，怎么回复？','不要给通用数字。先询问国家、产品、尺寸或颜色、数量和应用，再由工厂确认对应SKU的价格与MOQ。','价格 MOQ 报价 起订量',1],
['销售SOP','样品政策怎么说？','可以讨论实物样品，样品费可在正式大货订单中全额抵扣。样品型号、尺寸、快递费和发出时间必须逐单确认。','样品 寄样 样品费',1],
['销售SOP','询盘回复后如何推进下一步？','每次回复必须有一个明确动作：补充规格、选择目录、确认样品、准备报价或约定跟进时间，并记录当前阶段和下一步。','跟进 下一步 CRM 目录'],
['内容SOP','Facebook 内容应该怎么写？','每条尽量包含产品、应用、客户类型、一个具体卖点和明确CTA。工厂口播可以直接，但必须画面与事实匹配；发布前由负责人确认。','Facebook 帖子 内容 发布'],
['内容SOP','一篇合格的 SEO/GEO 文章需要什么？','回答一个真实采购问题；开头直接给答案；加入第一手证据、决策表或清单、相关内链、作者与审核人、结构化数据，并以询盘动作结尾。','SEO GEO Google 文章'],
['内容SOP','Luvie 的视觉规范是什么？','纯白#FFFFFF、深炭灰#333639、浅灰#F2F3F4；暖木棕#A68C74只做按钮和小面积高亮。优先原创产品、工厂和场景素材。','设计 颜色 视觉 图片'],
['订单流程','订单合作的五步流程是什么？','提交询价 → 样品确认 → 签订中英文合同 → 生产与出货前质检 → FOB/CIF物流发货。所有具体费用、交期和规格按订单确认。','订单 流程 合同 生产 物流',1],
['红线规则','哪些动作绝对不能未经同意执行？','不能擅自发送WhatsApp或Email、发布Facebook、回复客户私信、修改正式官网、修改报价合同发票、删除客户数据、确认订单或付款。','禁止 红线 发送 发布 删除'],
['红线规则','客户资料如何保密？','客户姓名、邮箱、WhatsApp、采购量、报价、订单、价格、付款和物流信息默认保密。公开案例必须匿名化。','隐私 客户资料 保密'],
['红线规则','哪些产品承诺必须人工确认？','价格、MOQ、实时库存、生产交期、尺寸、性能等级、质保、目的国认证、防火等级和环保声明都必须按具体产品和订单确认。','承诺 认证 防火 库存 交期',1]
];
const views={home:'首页',onboarding:'新员工入职',sop:'SOP中心',media:'资料中心',boss:'老板视图'};let state={view:'home',cat:'全部',q:'',selected:null};
const app=document.querySelector('#app'),nav=document.querySelector('#nav');
function go(view){state.view=view;render()}document.addEventListener('click',e=>{const v=e.target.closest('[data-view]')?.dataset.view;if(v)go(v)});
function navHtml(){nav.innerHTML=Object.entries(views).map(([k,v])=>`<button data-view="${k}" class="${state.view===k?'active':''}">${v}</button>`).join('')}
function answer(e){return `<article class="answer"><header><span>${e[0]}</span>${e[4]?'<b>需要人工确认</b>':''}</header><h2>${e[1]}</h2><p>${e[2]}</p><footer>知识来源：Luvie 已确认知识与内部SOP</footer></article>`}
function home(){return `<section class="hero"><div><p class="eyebrow">LUVIE KNOWLEDGE OS</p><h1>公司的知识，<br><em>每个人都找得到。</em></h1><p class="lead">让新员工快速上手，让老板看清基础动作，让同事随时找到统一答案、SOP和资料。拿到网址即可全球访问，不绑定GPT邮箱或指定IP。</p></div><div class="role-grid"><button data-view="onboarding"><b>01</b><strong>我是新员工</strong><span>从公司、产品到红线，5天完成入门</span></button><button data-view="boss"><b>02</b><strong>我是老板</strong><span>查看基础动作、知识资产和执行重点</span></button><button data-view="sop"><b>03</b><strong>我要找答案</strong><span>搜索产品、客户回复、内容与订单流程</span></button></div></section><section class="searchbox"><label>直接问知识库</label><div class="searchrow"><input id="home-q" placeholder="例如：客户问MOQ怎么回复？"><button id="home-search">查答案</button></div><p class="hint">涉及价格、库存、交期和认证时，知识库会提示人工确认。</p><div id="home-answer"></div></section><section class="stats"><div><strong>25年</strong><span>制造经验</span></div><div><strong>50+</strong><span>服务国家</span></div><div><strong>90%</strong><span>准时交付</span></div><div><strong>6条</strong><span>核心产品线</span></div></section>`}
function onboarding(){const s=[['第1天','认识公司与产品','掌握公司定位、六条产品线、统一联系方式和已确认事实。'],['第2天','学习询盘处理','会判断客户、追问需求、选择目录，并识别高风险问题。'],['第3天','熟悉内容与品牌','理解Facebook、SEO/GEO和视觉规范。'],['第4天','理解订单流程','掌握询价、样品、合同、生产质检和物流发货。'],['第5天','通过红线检查','识别发送、发布、隐私、价格和承诺风险。']];return page('ONBOARDING','新员工 5 天入职路径','先理解公司为什么这样做，再学习每天怎么做。',`<div class="timeline">${s.map(x=>`<article><b>${x[0]}</b><h2>${x[1]}</h2><p>${x[2]}</p></article>`).join('')}</div><div class="notice"><strong>入职通过标准</strong>能正确介绍公司和产品；能处理基础询盘；能找到对应SOP；知道哪些动作需要负责人确认；不会擅自发送、发布或承诺。</div>`)}
function sop(){const cats=['全部',...new Set(entries.map(e=>e[0]))],list=entries.filter(e=>(state.cat==='全部'||e[0]===state.cat)&&(!state.q||`${e[1]} ${e[2]} ${e[3]}`.toLowerCase().includes(state.q.toLowerCase())));return page('SOP CENTER','统一动作，统一答案','搜索公司事实、产品知识、销售回复、内容规范、订单流程和红线规则。',`<div class="searchrow"><input id="sop-q" value="${state.q}" placeholder="输入问题、产品或工作动作"><button id="sop-search">搜索</button></div><div class="tabs">${cats.map(c=>`<button data-cat="${c}" class="${state.cat===c?'active':''}">${c}</button>`).join('')}</div>${state.selected?answer(state.selected):''}<div class="grid">${list.map((e,i)=>`<button class="card" data-entry="${entries.indexOf(e)}"><small>${e[0]}</small><h2>${e[1]}</h2><p>${e[2].slice(0,75)}…</p></button>`).join('')}</div>`)}
function media(){return page('RESOURCE CENTER','图片、视频与文档资料中心','公开阅读版负责让团队随时访问；新增与修改资料由管理员统一处理。',`<div class="notice"><strong>资料可统一放在这里</strong>支持产品图、纹理特写、工厂视频、培训视频、PDF目录、Word、PPT和Excel。公开版暂不开放匿名上传，以免外部人员删除、覆盖或上传不安全文件。管理员请使用独立管理入口上传，员工始终通过本页面查看最新版。</div>`)}
function boss(){const cards=[['销售基础','每条询盘都有下一步','判断客户类型；问清产品和数量；明确目录、样品或报价；记录跟进时间。'],['内容基础','内容是否指向询盘','具体产品和客户；真实证据；统一CTA；负责人审核后发布。'],['交付基础','承诺是否有依据','价格、MOQ和库存逐单确认；样品合同一致；质检记录完整。'],['知识资产',`${entries.length} 条核心知识`,'覆盖公司、产品、销售、内容、订单与红线；配套5天入职路径。']];return page('MANAGEMENT VIEW','老板需要看清的基础动作','不是看热闹数据，而是确认团队有没有按统一方法持续执行。',`<div class="grid boss">${cards.map(x=>`<article class="card"><small>${x[0]}</small><h2>${x[1]}</h2><p>${x[2]}</p></article>`).join('')}</div>`)}
function page(k,t,c,body){return `<section class="section"><header class="page-head"><p class="eyebrow">${k}</p><h1>${t}</h1><p class="lead">${c}</p></header>${body}</section>`}
function bind(){document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{state.cat=b.dataset.cat;render()});document.querySelectorAll('[data-entry]').forEach(b=>b.onclick=()=>{state.selected=entries[+b.dataset.entry];render()});const hs=document.querySelector('#home-search');if(hs)hs.onclick=()=>{const q=document.querySelector('#home-q').value.trim();const e=entries.find(x=>`${x[1]} ${x[2]} ${x[3]}`.toLowerCase().includes(q.toLowerCase()))||entries[0];document.querySelector('#home-answer').innerHTML=answer(e)};const ss=document.querySelector('#sop-search');if(ss)ss.onclick=()=>{state.q=document.querySelector('#sop-q').value.trim();render()}}
function render(){navHtml();app.innerHTML=state.view==='home'?home():state.view==='onboarding'?onboarding():state.view==='sop'?sop():state.view==='media'?media():boss();bind();scrollTo({top:0,behavior:'smooth'})}render();
